@id = 67e1f12f40c84d748819a64b 

### Create a new Todo
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "title": "Sample Todo"
}

### Get all Todos
GET http://localhost:3000/api/todos

### Get Todo by ID
GET http://localhost:3000/api/todos/{{id}}

### Update Todo
PUT http://localhost:3000/api/todos/{{id}}
Content-Type: application/json

{
  "title": "Updated Todo Title"
}

### Delete a Todo
# Replace {{id}} with the actual ID of the Todo you want to delete
DELETE http://localhost:3000/api/todos/{{id}}

### Create a new Todo (Invalid - Missing Title)
POST http://localhost:3000/api/todos
Content-Type: application/json

{}

### Update Todo (Invalid - Missing Title)
PUT http://localhost:3000/api/todos/{{id}}
Content-Type: application/json

{}