name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Node Todo API CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run linting
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run tests
      - name: Run tests
        env:
          MONGODB_URI: mongodb://admin:admin@localhost:27017/todoDB?authSource=admin
        run: npm test

  mongodb:
    name: MongoDB Service
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand("ping")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3